if("undefined"===typeof bu||"undefined"===typeof bu.plugins.navigation||"undefined"===typeof bu.plugins.navigation.tree)throw new TypeError("BU Navigation Manager script dependencies have not been met!");
(function(b){bu.plugins.navigation.views=bu.plugins.navigation.views||{};var g,d,c;g=bu.plugins.navigation.views.Navman={el:"#nav-tree-container",ui:{form:"#navman_form",noticesContainer:"#navman-notices",movesField:"#navman-moves",insertsField:"#navman-inserts",updatesField:"#navman-updates",deletionsField:"#navman-deletions",expandAllBtn:"#navman_expand_all",collapseAllBtn:"#navman_collapse_all"},data:{dirty:!1,deletions:[],insertions:{},updates:{},moves:{}},initialize:function(){var a=this.settings=
bu_navman_settings;a.el=this.el;c=bu.plugins.navigation.tree("navman",a);d.initialize({allowTop:!!a.allowTop,isSectionEditor:!!a.isSectionEditor});c.listenFor("editPost",b.proxy(this.editPost,this));c.listenFor("postRemoved",b.proxy(this.postRemoved,this));c.listenFor("postMoved",b.proxy(this.postMoved,this));d.listenFor("linkInserted",b.proxy(this.linkInserted,this));d.listenFor("linkUpdated",b.proxy(this.linkUpdated,this));b(this.ui.form).bind("submit",b.proxy(this.save,this));b(this.ui.expandAllBtn).bind("click",
this.expandAll);b(this.ui.collapseAllBtn).bind("click",this.collapseAll);a=this.settings.imagesUrl+"/progress.gif";this.$spinner=b('<img alt="Processing..."/>');this.$spinner[0].src=a},expandAll:function(a){a.preventDefault();a.stopImmediatePropagation();c.showAll()},collapseAll:function(a){a.preventDefault();a.stopImmediatePropagation();c.hideAll()},editPost:function(a){"link"===a.type?d.edit(a):window.location="post.php?action=edit&post="+a.ID},linkInserted:function(a){this.data.insertions[a.ID]=
a;this.data.dirty=!0},linkUpdated:function(a){"new"===a.status?this.data.insertions[a.ID]=a:this.data.updates[a.ID]=a;this.data.dirty=!0},postRemoved:function(a){if(a=a.ID)"undefined"!==typeof this.data.insertions[a]?delete this.data.insertions[a]:("undefined"!==typeof this.data.updates[a]?delete this.data.updates[a]:"undefined"!==typeof this.data.moves[a]&&delete this.data.moves[a],this.data.deletions.push(a),this.data.dirty=!0)},postMoved:function(a){if("new"!==a.status&&(a.parent!==a.originalParent||
a.menu_order!==a.originalOrder))this.data.moves[a.ID]=a,this.data.dirty=!0},save:function(){var a=this.data.deletions,h={},e={},d={},f;b.each(this.data.insertions,function(a){(f=c.getPost(a))&&(d[f.ID]=f)});b.each(this.data.updates,function(a){(f=c.getPost(a))&&(e[f.ID]=f)});b.each(this.data.moves,function(a){(f=c.getPost(a))&&(h[f.ID]=f)});b(this.ui.deletionsField).attr("value",JSON.stringify(a));b(this.ui.insertsField).attr("value",JSON.stringify(d));b(this.ui.updatesField).attr("value",JSON.stringify(e));
b(this.ui.movesField).attr("value",JSON.stringify(h));a=b("<span>Saving navigation changes...</span>").prepend(this.$spinner);this.notice(a.html(),"message");c.lock();this.data.dirty=!1},notice:function(a,c,e){var e=e||!0,d=b(this.ui.noticesContainer);e&&d.empty();d.append('<div class="'+("message"===c?"updated fade":"error")+' below-h2"><p>'+a+"</p></div>")}};d=bu.plugins.navigation.views.Linkman={el:"#navman-link-editor",ui:{form:"#navman_editlink_form",addBtn:"#navman_add_link",urlField:"#editlink_address",
labelField:"#editlink_label",targetNewField:"#editlink_target_new",targetSameField:"#editlink_target_same"},data:{currentLink:null,allowTop:!0,isSectionEditor:!1},initialize:function(a){a=a||{};b.extend(!0,this.data,a);bu.signals.register(this);this.$el=b(this.el);this.$form=b(this.ui.form);this.$el.dialog({autoOpen:!1,buttons:{Ok:b.proxy(this.save,this),Cancel:b.proxy(this.cancel,this)},minWidth:400,width:500,modal:!0,resizable:!1});b(document.body).delegate(".ui-widget-overlay, .ui-widget","click",
this.stopPropagation);b(this.ui.addBtn).bind("click",b.proxy(this.add,this));c.listenFor("postSelected",b.proxy(this.onPostSelected,this));c.listenFor("postDeselected",b.proxy(this.onPostDeselected,this));c.listenFor("postsDeselected",b.proxy(this.onPostDeselected,this))},add:function(a){a.preventDefault();a.stopPropagation();this.data.currentLink={status:"new",type:"link",meta:{}};this.$el.dialog("option","title","Add a Link").dialog("open")},edit:function(a){b(this.ui.urlField).attr("value",a.content);
b(this.ui.labelField).attr("value",a.title);"new"===a.meta.bu_link_target?b(this.ui.targetNewField).attr("checked","checked"):b(this.ui.targetSameField).attr("checked","checked");this.data.currentLink=a;this.$el.dialog("option","title","Edit a Link").dialog("open")},save:function(a){a.preventDefault();a.stopPropagation();if(this.$form.valid()){var a=this.data.currentLink,d;a.content=b(this.ui.urlField).attr("value");a.title=b(this.ui.labelField).attr("value");a.meta.bu_link_target=b("input[name='editlink_target']:checked").attr("value");
(d=c.getSelectedPost())?(a.parent=d.parent,a.menu_order=d.menu_order+1):(a.parent=0,a.menu_order=1);"new"===a.status&&!a.ID?(a=c.insertPost(a),this.broadcast("linkInserted",[a])):(a=c.updatePost(a),this.broadcast("linkUpdated",[a]));this.clear();this.$el.dialog("close")}},cancel:function(a){a.preventDefault();a.stopPropagation();this.$el.dialog("close");this.clear()},clear:function(){b(this.ui.urlField).attr("value","");b(this.ui.labelField).attr("value","");b(this.ui.targetSameField).attr("checked",
"checked");b(this.ui.targetNewField).removeAttr("checked");this.data.currentLink=null},onPostSelected:function(a){var d=c.getPost(a.parent),e=this.data.allowTop||0!=a.parent;(e=bu.hooks.applyFilters("navmanCanAddLink",e,a,d))&&b(this.ui.addBtn).parent("li").removeClass("disabled")},onPostDeselected:function(){var a=this.data.allowTop;(a=bu.hooks.applyFilters("navmanCanAddLink",a))||b(this.ui.addBtn).parent("li").addClass("disabled")},stopPropagation:function(a){a.stopPropagation()}};window.onbeforeunload=
function(){if(g.data.dirty)return"You have made changes to your navigation that have not yet been saved."}})(jQuery);jQuery(document).ready(function(){bu.plugins.navigation.views.Navman.initialize()});