var navman=null,navman_dirty=!1,navman_links=[],navman_delete=[],navman_edits={},navman_editing=null;function showPageDetail(b){jQuery("#navman_pagedetail h3").html(b.post_title);jQuery("#navman_drop_target").html(b.post_title);jQuery("#navman_drop").attr("rel",b.ID);jQuery("#navman_pagedetail").show()}function hidePageDetail(){jQuery("#navman_pagedetail").hide()}
function editNode(b){var a=jQuery(b);if(a.attr("rel")==="link")if(a.is('[class*="newlink_"]')){if(b=/newlink_(\d+)/,b=b.exec(a.attr("class"))[1]){var d=navman_links[b];jQuery("#editlink_id").attr("value","newlink_"+b);jQuery("#editlink_address").attr("value",d.address);jQuery("#editlink_label").attr("value",d.label);d.target=="new"?jQuery("#editlink_target_new").attr("checked","checked"):jQuery("#editlink_target_same").attr("checked","checked");navman_editing=a;jQuery("#navman_editlink").dialog("open")}}else b=
/^p(\d+)/,(b=b.exec(a.attr("id"))[1])&&navman_edits[b]?(jQuery("#editlink_id").attr("value",navman_edits[b].ID),jQuery("#editlink_address").attr("value",navman_edits[b].post_content),jQuery("#editlink_label").attr("value",navman_edits[b].post_title),navman_edits[b].target=="new"?jQuery("#editlink_target_new").attr("checked","checked"):jQuery("#editlink_target_same").attr("checked","checked"),navman_editing=a,jQuery("#navman_editlink").dialog("open")):jQuery.getJSON(rpcPageURL,{id:a.attr("id")},function(b){jQuery("#editlink_id").attr("value",
b.ID);jQuery("#editlink_address").attr("value",b.post_content);jQuery("#editlink_label").attr("value",b.post_title);b.target=="new"?jQuery("#editlink_target_new").attr("checked","checked"):jQuery("#editlink_target_same").attr("checked","checked");navman_editing=a;jQuery("#navman_editlink").dialog("open")});else b=/^p(\d+)/,b=b.exec(a.attr("id"))[1],window.location="post.php?action=edit&post="+b}
jQuery(document).ready(function(){jQuery("#navman_editlink").dialog({autoOpen:!1,buttons:{Ok:function(){if(jQuery("#navman_editlink_form").valid()){if(jQuery("#editlink_id").attr("value").indexOf("newlink_")!=-1){var a=/newlink_(\d+)/.exec(jQuery("#editlink_id").attr("value"))[1];a&&(navman_links[a]={address:jQuery("#editlink_address").attr("value"),label:jQuery("#editlink_label").attr("value"),target:jQuery("input[name='editlink_target']:checked").attr("value")},$navman.jstree("rename_node",navman_editing,
navman_links[a].label))}else a={ID:jQuery("#editlink_id").attr("value"),post_title:jQuery("#editlink_label").attr("value"),post_content:jQuery("#editlink_address").attr("value"),target:jQuery("input[name='editlink_target']:checked").attr("value")},navman_edits[a.ID]=a,$navman.jstree("rename_node",navman_editing,a.post_title);jQuery("#navman_editlink").dialog("close");jQuery("#editlink_id").attr("value","");jQuery("#editlink_address").attr("value","");jQuery("#editlink_label").attr("value","");jQuery("#editlink_target_same").attr("checked",
"");navman_dirty=!0;navman_editing=null}},Cancel:function(){jQuery("#navman_editlink").dialog("close");jQuery("#editlink_id").attr("value","");jQuery("#editlink_address").attr("value","");jQuery("#editlink_label").attr("value","");jQuery("#editlink_target_same").attr("checked","");navman_editing=null}},minWidth:400,width:500,modal:!0,resizable:!1});jQuery("div.inner-sidebar").show();hidePageDetail();var b={themes:{theme:"classic"},core:{animation:0,html_titles:!0},plugins:["themes","json_data","ui",
"contextmenu","types","dnd","crrm"],types:{types:{"default":{clickable:!0,renameable:!0,deletable:!0,creatable:!0,draggable:!0,max_children:-1,max_depth:-1,valid_children:"all",icon:{image:interfacePath+"/icons/page_regular.png"}},folder:{clickable:!0,renameable:!1,deletable:!0,creatable:!0,draggable:!0,max_children:-1,max_depth:-1,valid_children:"all",icon:{image:interfacePath+"/icons/folder_regular.png"}},folder_excluded:{clickable:!0,renameable:!1,deletable:!0,creatable:!0,draggable:!0,max_children:-1,
max_depth:-1,valid_children:"all",icon:{image:interfacePath+"/icons/folder_hidden.png"}},folder_restricted:{clickable:!0,renameable:!1,deletable:!0,creatable:!0,draggable:!0,max_children:-1,max_depth:-1,valid_children:"all",icon:{image:interfacePath+"/icons/folder_lock.png"}},folder_excluded_restricted:{clickable:!0,renameable:!1,deletable:!0,creatable:!0,draggable:!0,max_children:-1,max_depth:-1,valid_children:"all",icon:{image:interfacePath+"/icons/folder_hidden_restricted.png"}},page:{clickable:!0,
renameable:!1,deletable:!0,creatable:!0,draggable:!0,max_children:-1,max_depth:-1,valid_children:"all",icon:{image:interfacePath+"/icons/page_regular.png"}},page_excluded:{clickable:!0,renameable:!1,deletable:!0,creatable:!0,draggable:!0,max_children:-1,max_depth:-1,valid_children:"all",icon:{image:interfacePath+"/icons/page_hidden.png"}},page_restricted:{clickable:!0,renameable:!1,deletable:!0,creatable:!0,draggable:!0,max_children:-1,max_depth:-1,valid_children:"all",icon:{image:interfacePath+"/icons/page_restricted.png"}},
page_excluded_restricted:{clickable:!0,renameable:!1,deletable:!0,creatable:!0,draggable:!0,max_children:-1,max_depth:-1,valid_children:"all",icon:{image:interfacePath+"/icons/page_hidden_restricted.png"}},link:{icon:{image:interfacePath+"/icons/page_white_link.png"},max_children:0},link_restricted:{icon:{image:interfacePath+"/icons/page_white_link.png"},max_children:0}}},json_data:{data:pages,ajax:{url:rpcURL,type:"POST",data:function(a){return{id:a.attr?a.attr("id"):0}}},progressive_render:!0},
contextmenu:{items:function(){return{edit:{label:"Edit",action:editNode,icon:"remove"},remove:{label:"Remove",action:function(a){this.is_selected(a)?this.remove():this.remove(a)}}}}}};$navman=jQuery("#navman_container");$navman.bind("select_node.jstree",function(){jQuery("input[name='bu_navman_delete']").removeAttr("disabled");jQuery("input[name='bu_navman_edit']").removeAttr("disabled")});$navman.bind("deselect_node.jstree",function(){jQuery("input[name='bu_navman_delete']").attr("disabled","disabled");
jQuery("input[name='bu_navman_edit']").attr("disabled","disabled");hidePageDetail()});$navman.bind("remove.jstree",function(a,b){var c=/^p(\d+)/.exec(jQuery(b.rslt.obj).attr("id"))[1];c&&(navman_delete.push(c),navman_dirty=!0);console.log(navman_delete)});$navman.jstree(b);jQuery("#navman_expand_all").click(function(a){$navman.jstree("open_all");a.preventDefault();a.stopImmediatePropagation()});jQuery("#navman_collapse_all").click(function(a){$navman.jstree("close_all");a.preventDefault();a.stopImmediatePropagation()});
jQuery("#bu_navman_save").click(function(){navman_dirty=!1});jQuery("#navman_expand_all_b").click(function(a){$navman.jstree("open_all");a.preventDefault();a.stopImmediatePropagation()});jQuery("#navman_collapse_all_b").click(function(a){navman.jstree("close_all");a.preventDefault();a.stopImmediatePropagation()});jQuery("#bu_navman_save_b").click(function(){navman_dirty=!1});jQuery("#addlink_add").click(function(){if(jQuery("#navman_addlink_form").valid()){var a=jQuery("#addlink_address").attr("value").replace(/^\s+|\s+$/g,
""),b=jQuery("#addlink_label").attr("value").replace(/^\s+|\s+$/g,""),c=jQuery("input[name='addlink_target']:checked").attr("value");jQuery("#addlink_address").attr("value","");jQuery("#addlink_label").attr("value","");var e={attr:{rel:"link","class":"newlink_"+navman_links.length},data:{title:b}};navman_links.push({address:a,label:b,target:c});$navman.jstree("create",null,"after",e,null,!0);navman_dirty=!0}});jQuery("input[name='bu_navman_delete']").attr("disabled","disabled");jQuery("input[name='bu_navman_edit']").attr("disabled",
"disabled");jQuery("input[name='bu_navman_delete']").click(function(){$navman.jstree("remove")});jQuery("input[name='bu_navman_edit']").click(function(){var a=$navman.jstree("get_selected");editNode(a)});jQuery("#navman_form").submit(function(){var a=$navman.jstree("get_json",-1);jQuery("#navman_data").attr("value",JSON.stringify(a));jQuery("#navman_links").attr("value",JSON.stringify(navman_links));jQuery("#navman_delete").attr("value",JSON.stringify(navman_delete));jQuery("#navman_edits").attr("value",
JSON.stringify(navman_edits))})});window.onbeforeunload=function(){if(navman_dirty)return"You have made changes to your navigation that have not yet been saved."};
