if("undefined"===typeof bu||"undefined"===typeof bu.plugins||"undefined"===typeof bu.plugins.navigation)throw new TypeError("BU Navigation Metabox dependencies have not been met!");
(function(a){bu.plugins.navigation.views=bu.plugins.navigation.views||{};var d;bu.plugins.navigation.views.Metabox={el:"#bupageparentdiv",ui:{treeContainer:"#edit_page_tree",moveBtn:"#select-parent",breadcrumbs:"#bu_nav_attributes_location_breadcrumbs"},inputs:{label:'[name="nav_label"]',visible:'[name="nav_display"]',postID:'[name="post_ID"]',originalStatus:'[name="original_post_status"]',parent:'[name="parent_id"]',order:'[name="menu_order"]',autoDraft:'[name="auto_draft"]'},data:{modalTree:void 0,
breadcrumbs:"",label:""},initialize:function(){var b,c,d,h,g;this.settings=nav_metabox_settings;this.settings.el=this.ui.treeContainer;this.settings.isNewPost=1==a(this.inputs.autoDraft).val()?!0:!1;b=a(this.inputs.originalStatus).val();c=parseInt(a(this.inputs.parent).val(),10);d=parseInt(a(this.inputs.order).val(),10);h=a(this.inputs.label).val()||"(no title)";g=a(this.inputs.visible).attr("checked")||!1;this.settings.currentPost={ID:parseInt(a(this.inputs.postID).val(),10),title:h,status:"auto-draft"==
b?"new":b,parent:c,menu_order:d,meta:{excluded:!g},originalParent:c,originalExclude:!g};this.$el=a(this.el);this.loadNavTree();this.attachHandlers()},loadNavTree:function(){"undefined"===typeof this.data.modalTree&&(this.data.modalTree=ModalPostTree(this.settings),this.data.modalTree.listenFor("locationUpdated",a.proxy(this.onLocationUpdated,this)))},attachHandlers:function(){this.$el.delegate(this.ui.moveBtn,"click",this.data.modalTree.open);this.$el.delegate(this.inputs.label,"blur",a.proxy(this.onLabelChange,
this));this.$el.delegate(this.inputs.visible,"click",a.proxy(this.onToggleVisibility,this))},onLabelChange:function(){var b=a(this.inputs.label).attr("value");this.settings.currentPost.title=b;d.updatePost(this.settings.currentPost);d.save();this.updateBreadcrumbs(this.settings.currentPost)},onToggleVisibility:function(b){var c=a(b.target).attr("checked");c&&!this.isAllowedInNavigationLists(this.settings.currentPost)?(b.preventDefault(),this.notify('Displaying top-level pages in the navigation is disabled. To change this behavior, go to Site Design > Primary Navigation and enable "Allow Top-Level Pages."')):
(this.settings.currentPost.meta.excluded=!c,d.updatePost(this.settings.currentPost),d.save())},onLocationUpdated:function(b){a(this.inputs.parent).val(b.parent);a(this.inputs.order).val(b.menu_order);this.updateBreadcrumbs(b);this.settings.currentPost=b},updateBreadcrumbs:function(b){var b=d.getAncestors(b.ID),c=b.join("&nbsp;&raquo;&nbsp;");1<b.length?a(this.ui.breadcrumbs).html("<p>"+c+"</p>"):a(this.ui.breadcrumbs).html("<p>Top level page</p>")},isAllowedInNavigationLists:function(a){return!(!1===
a.originalExclude&&0===a.originalParent)&&0===a.parent?this.settings.allowTop:!0},notify:function(a){alert(a)}};ModalPostTree=bu.plugins.navigation.views.ModalPostTree=function(b){var c={},e=c.conf={treeContainer:"#edit_page_tree",toolbarContainer:".page_location_toolbar",navSaveBtn:"#bu_page_parent_save",navCancelBtn:"#bu_page_parent_cancel"},e=a.extend(e,b);a.extend(!0,c,bu.signals);c.open=function(b){var e=a(window).width(),i=a(window).height(),e=720<e?720:e,j=b.target.title||b.target.name||null,
f=b.target.href||b.target.alt,b=b.target.rel||!1,f=f.replace(/&width=[0-9]+/g,""),f=f.replace(/&height=[0-9]+/g,"");tb_show(j,f+"&width="+(e-80)+"&height="+(i-85),b);d.scrollToSelection();a("#TB_window").bind("unload tb_unload",function(){c.saving?c.saving=!1:d.restore()});return!1};c.onUpdateLocation=function(a){a.preventDefault();c.broadcast("locationUpdated",[d.getCurrentPost()]);d.save();c.saving=!0;tb_remove()};c.onCancelMove=function(a){a.preventDefault();tb_remove()};d=bu.plugins.navigation.tree("edit_post",
e);b=a(e.toolbarContainer);b.delegate(e.navSaveBtn,"click",c.onUpdateLocation);b.delegate(e.navCancelBtn,"click",c.onCancelMove);return c}})(jQuery);var tb_position;
(function(a){tb_position=function(){var d=a("#TB_window"),b=a(window).width(),c=a(window).height(),e=720<b?720:b;d.size()&&(d.width(e-50).height(c-45),a("#TB_inline").width(e-80).height(c-90),d.css({"margin-left":"-"+parseInt((e-50)/2,10)+"px"}),"undefined"!=typeof document.body.style.maxWidth&&d.css({top:"20px","margin-top":"0"}));return a("a.thickbox").each(function(){var b=a(this).attr("href");b&&(b=b.replace(/&width=[0-9]+/g,""),b=b.replace(/&height=[0-9]+/g,""),a(this).attr("href",b+"&width="+
(e-80)+"&height="+(c-85)))})};a(window).resize(function(){tb_position()})})(jQuery);jQuery(document).ready(function(){bu.plugins.navigation.views.Metabox.initialize()});