---
exclude_paths:
- tests/
- languages/
- vendor/
- js/vendor/
- "*.min.css"
- "*.min.js"

prepare:
  fetch:
  - "https://raw.githubusercontent.com/bu-ist/coding-standards/master/code-climate-rule-sets/.eslintrc"
  - "https://raw.githubusercontent.com/bu-ist/coding-standards/master/code-climate-rule-sets/.eslintignore"

engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
    channel: eslint-3
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: php
      standard: WordPress
      ignore_warnings: false
      encoding: utf-8
  phpmd:
    enabled: true
    config:
      file_extensions: php
      rulesets: codesize,naming,unusedcode
ratings:
  paths:
  - "**.js"
  - "**.php"
  - "**.css"
