language: php

sudo: false

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0

env:
    - WP_VERSION=4.1.13 WP_MULTISITE=0
    - WP_VERSION=4.1.13 WP_MULTISITE=1
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=nightly WP_MULTISITE=0
    - WP_VERSION=nightly WP_MULTISITE=1

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

install:
  - composer install --prefer-dist

before_script:
  - git config --global user.email "travis-ci@codeclimate.com"
  - git config --global user.name "Travis CI"
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit

after_script:
  - ./bin/codeclimate.sh

addons:
  codeclimate:
    repo_token: CODECLIMATE_REPO_TOKEN